🎒 Add contract events to generate-hooks output
TrueFiEng/useDApp pull request #1074
Opened 2023-01-31 22:28 UTC by tjvsx

- #1070 

closes #1070

2023-02-01 12:38 UTC, yivlad requested changes
Please add changeset

2023-02-01 12:38 UTC, yivlad commented on packages/core/generate-hooks/generate.ts
> +  event: {
I guess it would look better if the field was named `events`

2023-02-03 07:56 UTC, tjvsx commented
should be all set!

2023-02-06 16:15 UTC, pawelpolak2 approved these changes

2023-02-06 16:15 UTC, pawelpolak2 approved these changes

2023-02-06 17:01 UTC, merged