💌 Add notification example to our docs
TrueFiEng/useDApp pull request #625
Opened 2022-03-25 15:44 UTC by mj426382

2022-03-25 15:49 UTC, rzadp commented on packages/docs/src/examples/Notifications.tsx
> +                console.log(notification)
```suggestion
```

2022-03-25 15:50 UTC, rzadp commented on packages/docs/src/examples/Notifications.tsx
> +    const [nots, setNots] = useState([])
Weird shorthand

```suggestion
    const [notifications, setNotifications] = useState([])
```

2022-03-25 16:14 UTC, rzadp commented on packages/docs/src/examples/Notifications.tsx
> +        const filteredArray = mergedArray.filter(function(el , id){
```suggestion
        const uniqueNotifications = mergedArray.filter(function(el , id){
```

2022-03-28 08:20 UTC, rzadp requested changes
@mj426382 Can you set configuration `expirationPeriod` to 0, and implement `useNotifications` so that the notifications do not expire? Then we don't need to track `allNotifications` in the example.

2022-03-28 08:21 UTC, rzadp requested changes

2022-03-28 08:21 UTC, rzadp commented on packages/docs/docs/guides/transactions.mdx
> +App will deposit 1 wei to Wrapped Ether contract.
```suggestion
App will deposit 1 wei to Wrapped Ether contract and display transaction notification.
```

This is the main thing of the example, should be said upfront.

2022-03-28 08:21 UTC, rzadp commented on packages/docs/docs/guides/transactions.mdx
> +The app will also display transaction notifications.
```suggestion
```

2022-03-28 08:24 UTC, rzadp commented
<img width="847" alt="Screenshot 2022-03-28 at 10 23 32" src="https://user-images.githubusercontent.com/12039224/160357012-2d754e14-3330-4c0e-ad8b-de214d583833.png">

This is `constants/Weth.ts` file right? Should be titled, like `App.tsx` is.

2022-03-28 11:15 UTC, rzadp commented
Please remove `id` from table

2022-03-28 13:38 UTC, rzadp approved these changes

2022-03-28 14:35 UTC, dmaretskyi approved these changes

2022-03-28 14:47 UTC, merged

2022-04-02 03:21 UTC, KevinsBobo commented
https://github.com/TrueFiEng/useDApp/commit/751327e7f84ec1a947deb2689467f85f9bc65f1a#r70259189
This change introduces new problems:
https://github.com/TrueFiEng/useDApp/issues/640

2022-04-05 12:37 UTC, rzadp commented
> [751327e#r70259189](https://github.com/TrueFiEng/useDApp/commit/751327e7f84ec1a947deb2689467f85f9bc65f1a#r70259189) This change introduces new problems: #640

Addressed by https://github.com/TrueFiEng/useDApp/pull/655